TRAIN:
  ENABLE: False
  DATASET: Actortracks
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: '/cluster/work/cvl/gusingh/pretrained_models/slowfast-kinetics/SLOWFAST_8x8_R50.pkl'
  CHECKPOINT_TYPE: caffe2
  # CHECKPOINT_FILE_PATH: '/cluster/work/cvl/gusingh/pretrained_models/slowfast-mit/SLOWFAST_8x8_R50.pyth'
  # CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
  ROI_HEAD_TYPE: 'TRACK'
AVA:
  SUB_DATASET: 'multisports'
  DETECTION_SCORE_THRESH: 0.1
  FRAME_DIR: ""
  ANNOTATION_DIR: "/cluster/work/cvl/gusingh/data/ava-kinetics/annotations/"
  FRAME_LIST_DIR: "/cluster/work/cvl/gusingh/data/ava-kinetics/annotations/multisports_frame_lists/"
  LABEL_MAP_FILE: "multisports_actions.pbtxt"
  EXCLUSION_FILE: "ava_val_excluded_timestamps.csv"
  TEST_LISTS: ["val.csv"]
  FULL_TEST_ON_VAL: False
  TRAIN_PREDICT_BOX_LISTS: ["multisports_train_predicted_boxes_TRACKSbg8.csv",]
  TEST_PREDICT_BOX_LISTS: ["multisports_val_predicted_boxes_TRACKSbg1.csv"]
  TRAIN_GT_BOX_LISTS: ["multisports_train.csv"]
  GROUNDTRUTH_FILE: "multisports_val.csv"
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 8
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00001
  WARMUP_EPOCHS: 2.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 4
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "./outputs/"
